### ISSUE TITLE
Issue Import QuakeMigrate in Python (AttributeError)

### ISSUE THREAD

**Issue by PhilCryo** [QuakeMigrate/QuakeMigrate#140]
Hi,

I'm trying to install QuakeMigrate on my DEBIAN GNU/Linux 10 machine and I'm using the Installation docs on the website to do so.

I have managed to create an environment and activate it and the installation from source seems to be also a success. However when I want to import quakemigrate in a Python session, I have the following error :

**" AttributeError: 'numpy.int64' object has no attribute 'split' "**

Here is my last process of installation :

(quakemigrate) [peltierp@ige-osugb-s-242]:~/Documents/QuakeMigrate-master$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import quakemigrate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peltierp/Documents/QuakeMigrate-master/quakemigrate/__init__.py", line 16, in <module>
    from quakemigrate.io.data import Archive  # NOQA
  File "/home/peltierp/Documents/QuakeMigrate-master/quakemigrate/io/__init__.py", line 31, in <module>
    from .availability import read_availability, write_availability  # NOQA
  File "/home/peltierp/Documents/QuakeMigrate-master/quakemigrate/io/availability.py", line 15, in <module>
    from obspy import UTCDateTime
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/home/peltierp/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'

 - Operating System: Debian GNU/ Linux 10
 - Python version: 3.8.13
 - QuakeMigrate version: 1.0.0

Do you have any idea what might have gone wrong ?

Philémon

**Comment by TomWinder** [comment]
Hi Philémon,

Thanks for submitting this here. The issue is a known compatibility problem between obspy and numpy: https://github.com/obspy/obspy/issues/2912

Please confirm your numpy and obspy versions (e.g. using `conda list`), and update obspy or downgrade numpy to solve the problem (as described in the above issue). We will look at adding a version pin to prevent this happening in future.

**Comment by PhilCryo** [comment]
Thanks for the reply! 
Indeed the problem was an incompatibility between versions of Obspy (1.2.2) and Numpy (1.22).
