### ISSUE TITLE
BUG: plotting failure with matplotlib 3.8

### ISSUE THREAD

**Issue by TomWinder** [QuakeMigrate/QuakeMigrate#162]
**Describe the bug**
Plotting syntax used throughout trigger/pick/locate summary plots is outdated as of matplotlib 3.8 (niche case not highlighted by a deprecation warning).

**To Reproduce**
Fresh installation of QuakeMigrate in Python 3.10/11 with matplotlib 3.8, run detect (should work normally) and then trigger - which will fail in the plotting stage with the following message:

```
...
	Plotting trigger summary...
Traceback (most recent call last):
  File "/Users/tom/Software/QuakeMigrate/examples/Volcanotectonic_Iceland/dike_intrusion_trigger.py", line 59, in <module>
    trig.trigger(starttime, endtime, interactive_plot=False,
  File "/Users/tom/miniconda3/envs/py310_binder-check/lib/python3.10/site-packages/quakemigrate/signal/trigger.py", line 271, in trigger
    self._trigger_batch(batchstart, batchend, region, interactive_plot)
  File "/Users/tom/miniconda3/envs/py310_binder-check/lib/python3.10/site-packages/quakemigrate/signal/trigger.py", line 331, in _trigger_batch
    trigger_summary(
  File "/Users/tom/miniconda3/envs/py310_binder-check/lib/python3.10/site-packages/quakemigrate/util.py", line 658, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/py310_binder-check/lib/python3.10/site-packages/quakemigrate/plot/trigger.py", line 113, in trigger_summary
    ax.get_shared_x_axes().join(ax, fig.axes[2])
AttributeError: 'GrouperView' object has no attribute 'join'. Did you mean: 'joined'?
``` 

**Expected behavior**
Plotting should proceed without errors.

**Desktop (please complete the following information):**
 - Operating System: macOS 11.4 Big Sur
 - Python version: 3.10
 - QuakeMigrate version: 1.0.2 (installed through PyPI)

**Additional context**
Issue also encountered by @TomSHudson - and described in #161

**Comment by TomWinder** [comment]
From an initial look.. it seems like the explicit "join" lines might actually be unnecessary - because though they should be joined in each case, we then separately specify the axes positions, dimensions and tick parameters for every individual axes involved.

But given it's implied, and that they are treated like joined axes, I think it's safest to just implement the new syntax for doing this job (from https://matplotlib.org/stable/api/cbook_api.html#matplotlib.cbook.Grouper)

```
grp = Grouper()
grp.join(a, b)
```

This should avoid any backwards-compatibility issues, as it was the preferred syntax since matplotlib 3.6

**Comment by TomWinder** [comment]
So e.g. I think the change is in `quakemigrate/plot/phase_picks.py` [line 65]:

```diff
- axes[0].get_shared_x_axes().join(axes[0], axes[3])

+ from matplotlib.cbook import Grouper  ## should be at top of file with other mpl imports

+ grp = Grouper()
+ grp.join(axes[0], axes[3])
```
