### ISSUE TITLE
ValueError converting float NaN to integer in return of time in scan._phase_picker()

### ISSUE THREAD

**Issue by TomSHudson** [QuakeMigrate/QuakeMigrate#55]
An issue with running event relocation in QMigrate master branch. There appears to be an issue if the variable p_ttime[i] value = NaN. I'm not sure how the value became a NaN, and happy to look into it if necessary, but if the issue is known about then guess there must be a fairly easy fix.

Here is the exact error thrown:

========================================================================================================================
	EVENT - 1174 of 1393 - 20110720170018600000
========================================================================================================================

	Determining event location...

	Reading waveform data...
    	Elapsed time: 0.439387 seconds.

	Computing 4D coalescence grid...
    	Elapsed time: 15.360480 seconds.

	Making phase picks...
Traceback (most recent call last):
  File "run_QMigrate.py", line 224, in <module>
    run_locate(data_in, station_file, lut_out, out_path, run_name, locate_sampling_rate, p_bp_filter, s_bp_filter, p_onset_win, s_onset_win, time_step, locate_decimation, marginal_window=marginal_window, n_cores=n_cores)
  File "run_QMigrate.py", line 179, in run_locate
    scan.locate(starttime, endtime)
  File "/Users/eart0504/opt/anaconda3/envs/QMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.1.16-py3.6.egg/QMigrate/signal/scan.py", line 622, in locate
    self._locate_events(start_time, end_time)
  File "/Users/eart0504/opt/anaconda3/envs/QMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.1.16-py3.6.egg/QMigrate/signal/scan.py", line 926, in _locate_events
    phase_picks = self._phase_picker(event_max_coa)
  File "/Users/eart0504/opt/anaconda3/envs/QMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.1.16-py3.6.egg/QMigrate/signal/scan.py", line 1471, in _phase_picker
    p_arrival = event["DT"] + p_ttime[i]
  File "/Users/eart0504/opt/anaconda3/envs/QMigrate/lib/python3.6/site-packages/obspy/core/utcdatetime.py", line 966, in __add__
    return UTCDateTime(ns=self._ns + int(round(value * 1e9)))
ValueError: cannot convert float NaN to integer

**Comment by TomSHudson** [comment]
This is fixed in development branch so closing.

**Comment by hemmelig** [comment]
The root cause of this issue was the SciPy class "RegularGridInterpolator", which was used to interpolate values in the lookup table. Floating point errors can lead to values outside of the grid being passed to the interpolator. In such cases, the default behaviour of the regular grid interpolator is to return a NaN, leading to this issue. Instead, we have set the fill value to be "None" - the regular grid interpolator will now extrapolate a value from the closest grid node.

Issue resolved.
