### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by SeisVincent** [QuakeMigrate/QuakeMigrate#70]
Hello, guys:

When I run the locate part of icequake.py, it presents a FileNotFoundError problem. Do you know what is the reason for this problem, and how can I fix it?

Thank you very much.

The problem followed:
========================================================================================================================
========================================================================================================================
        LOCATE - Determining earthquake location and uncertainty
========================================================================================================================

        Parameters specified:
                Start time                = 2014-06-29T18:41:55.000000Z
                End   time                = 2014-06-29T18:42:20.000000Z
                Number of CPUs            = 12

========================================================================================================================

Traceback (most recent call last):
  File "icequake.py", line 142, in <module>
    scan.locate(starttime, endtime)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.6.14-py3.6.egg/QMigrate/signal/scan.py", line 622, in locate
    self._locate_events(start_time, end_time)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.6.14-py3.6.egg/QMigrate/signal/scan.py", line 840, in _locate_events
    trig_events = self.output.read_triggered_events(start_time, end_time)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/QMigrate-1.0.20.6.14-py3.6.egg/QMigrate/io/quakeio.py", line 434, in read_triggered_events
    events = pd.read_csv(fname)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home1/yangyg/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.6/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
FileNotFoundError: File b'outputs/runs/icequake_example/icequake_example_TriggeredEvents.csv' does not exist

**Comment by hemmelig** [comment]
Hi Vincent,

Thanks for opening this issue - the problem has been caused by a mismatch between the name of the TriggeredEvents.csv file output by the Trigger stage of QuakeMigrate, and the filename expected by the Locate stage. This problem is on our end. A quick fix would be to navigate to the directory `outputs/runs/icequake_example` and run:

`mv icequake_example_210-210_TriggeredEvents.csv icequake_example_TriggeredEvents.csv`

We are looking to release a new version of the package quite soon, in which this specific issue has been addressed properly (among many other general improvements). I would recommend that you install and test this version over the code currently on master, which is very much an alpha version of the package. If you would like some guidance on how to do that, I would be more than happy to help. You can reach me directly at conor.bacon@esc.cam.ac.uk.

If you run into further problems that require advice rather than fixes to the code please feel free to email me or Tom, another developer, at tom.winder@esc.cam.ac.uk or conor.bacon@esc.cam.ac.uk. We also have a QuakeMigrate workspace on Slack that you are welcome to join, where we would be happy to provide any additional guidance. Thanks for using the code!

**Comment by SeisVincent** [comment]
Hi Conor Bacon,

Got it, thank you very much for your help.
