### ISSUE TITLE
bug: incorrectly ordered picks caused locate run to die

### ISSUE THREAD

**Issue by tmgreenfield1101** [QuakeMigrate/QuakeMigrate#98]
When the autopicker picks the P-wave arrival to be afterf the S-wave arrival an error is thrown during the magnitude calculation. This causes the locate run to die even though you could be 95% of the way through.

**Comment by TomWinder** [comment]
This should already have been fixed here: https://github.com/QuakeMigrate/QuakeMigrate/commit/da3b907ea6a0ee1f695700c7430ace779f63cd0a

Please provide the error message and details of your run so we can identify the root cause - see https://github.com/QuakeMigrate/QuakeMigrate/blob/development/.github/ISSUE_TEMPLATE/bug_report.md for a guide on how to submit a useful bug report. This is a picking error, not a magnitudes error.

**Comment by tmgreenfield1101** [comment]
Traceback (most recent call last):
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/local_mag/amplitude.py", line 554, in _get_amplitude_windows
    assert p_pick < s_pick
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./locate.py", line 89, in <module>
    scan.locate(starttime=starttime, endtime=endtime)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/scan.py", line 328, in locate
    self._locate_events(starttime=starttime, endtime=endtime)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/scan.py", line 452, in _locate_events
    event, _ = self.mags.calc_magnitude(event, self.lut, self.run)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/util.py", line 360, in wrapper
    result = func(*args, **kwargs)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/local_mag/local_mag.py", line 189, in calc_magnitude
    amps = self.amp.get_amplitudes(event, lut)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/util.py", line 360, in wrapper
    result = func(*args, **kwargs)
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/local_mag/amplitude.py", line 315, in get_amplitudes
    windows, picked = self._get_amplitude_windows(station, i,
  File "/space/tg286/quake_migrate/QuakeMigrate/quakemigrate/signal/local_mag/amplitude.py", line 556, in _get_amplitude_windows
    raise util.PickOrderException(event.uid, station, p_pick, s_pick)
quakemigrate.util.PickOrderException: PickOrderException: The P-phase arrival-time pick is later than the S-phase arrival pick! Something has gone wrong. Event: 20200719222247800, station: FAGS, p_pick: 2020-07-19T22:22:49.129458Z, s_pick: 2020-07-19T22:22:49.109130Z. There is probably a bug with the picker.

This was the error message. The linked pull request fixes this by adding a very simple try-except test when looking for the picks. If they are the wrong way round then the station is ignored. 

The base is using an up-to-date fork from the qmigrate development branch. So the fix you reference has already been applied, suggesting it isn't the cause

**Comment by TomWinder** [comment]
Ok, thanks. We chose to keep a hard `assert` rather than a try / except to make sure we actually catch bugs like this, rather than them occurring silently. You should be able to resume your run from the point it stopped by just changing the start time / editing the triggered event file you supplied.

I'd like to diagnose the picking bug fully, so we can fix that. Please can you send the .picks file and pick plot for this event (or re-run locate for that event to send the pick plot if you didn't have that option switched on).

**Comment by tmgreenfield1101** [comment]
[20200719222247800_RK.FAGS.pdf](https://github.com/QuakeMigrate/QuakeMigrate/files/5219382/20200719222247800_RK.FAGS.pdf)
[20200719222247800.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/5219387/20200719222247800.txt)

**Comment by TomWinder** [comment]
Ok, this is explicitly the case that commit I mentioned previously should catch. But I think I see the cause. What sampling rate are you running at - 50Hz?

**Comment by tmgreenfield1101** [comment]
yep - 50 Hz

**Comment by TomWinder** [comment]
It will be faff to just pull the pick_fix branch, but please can you copy the change I have made there into your local gaussianpicker.py to check it fixes the issue.

**Comment by tmgreenfield1101** [comment]
yep - all sorted
